services:
  hypothesis-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hypothesis-frontend
    ports:
      - "15001:80"
    depends_on:
      - hypothesis-backend
    networks:
      - hypothesis-net

  hypothesis-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypothesis-backend
    # ports:
    #   - "8000:8000" # Removed for internal network isolation
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      hypothesis-db:
        condition: service_healthy
    networks:
      - hypothesis-net

  hypothesis-db:
    image: postgres:15-alpine
    container_name: hypothesis-db
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432" # Removed for internal network isolation
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d hypothesis_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hypothesis-net

  # This service is just to build the image that the backend will spawn
  hypothesis-pipeline-builder:
    profiles: [ "builder" ]
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    image: hypothesis-validator:latest
    networks:
      - hypothesis-net

networks:
  hypothesis-net:
    name: hypothesis-network
